import re
from collections import Counter

COMMON_ENGLISH_WORDS = {
    "a", "able", "about", "above", "abroad", "absent", "absolute", "absorb",
    "abstract", "abuse", "academic", "accept", "access", "accident", "account",
    "achieve", "acid", "across", "act", "action", "active", "activity", "actor",
    "actual", "actually", "add", "addition", "address", "adjust", "admit",
    "adopt", "adult", "advance", "advantage", "advertise", "advice", "advise",
    "affair", "affect", "afford", "afraid", "after", "afternoon", "afterwards",
    "again", "against", "age", "agency", "agent", "ago", "agree", "agreement",
    "ahead", "aid", "aim", "air", "airport", "alcohol", "alive", "all",
    "allow", "almost", "alone", "along", "already", "also", "alter",
    "alternative", "although", "altogether", "always", "amaze", "ambition",
    "among", "amount", "amuse", "analysis", "analyze", "ancient", "and",
    "anger", "angle", "animal", "announce", "annual", "another", "answer",
    "anxiety", "anxious", "any", "anybody", "anyone", "anything", "anyway",
    "anywhere", "apart", "apartment", "apologize", "apparent", "appeal",
    "appear", "appearance", "apple", "application", "apply", "appoint",
    "appreciate", "approach", "appropriate", "approval", "approve",
    "architecture", "area", "argue", "argument", "arise", "arm", "army",
    "arrange", "arrangement", "arrest", "arrival", "arrive", "art", "article",
    "artist", "artistic", "ashamed", "aside", "ask", "asleep", "aspect",
    "assist", "assistance", "assistant", "associate", "association", "assume",
    "assumption", "atmosphere", "attach", "attack", "attempt", "attend",
    "attention", "attitude", "attract", "attraction", "attractive", "audience",
    "aunt", "author", "authority", "automatic", "autumn", "available", "average",
    "avoid", "awake", "award", "aware", "away", "awful", "awkward",
    "back", "background", "backward", "bacteria", "bad", "badly", "bag",
    "balance", "ball", "ban", "band", "bank", "bar", "barely", "barrier",
    "base", "basic", "basically", "basis", "basket", "bath", "bathroom",
    "battle", "bay", "beach", "bear", "beast", "beat", "beautiful",
    "beauty", "become", "bed", "bedroom", "beer", "before", "beg", "begin",
    "beginning", "behalf", "behave", "behavior", "behind", "being", "belief",
    "believe", "bell", "belong", "below", "belt", "bench", "bend", "beneath",
    "benefit", "beside", "besides", "best", "bet", "better", "beyond", "bicycle",
    "bigger", "bill", "bin", "bird", "birth", "birthday", "bishop", "bit",
    "bite", "bitter", "black", "blade", "blame", "blank", "blind", "block",
    "blood", "blow", "blue", "board", "boat", "body", "boil", "bomb",
    "bond", "bone", "bonus", "book", "boost", "boot", "border", "bored",
    "boring", "born", "borrow", "boss", "both", "bother", "bottle",
    "bottom", "bound", "bowl", "box", "boy", "boyfriend", "brain", "branch",
    "brand", "brave", "bread", "break", "breakfast", "breath", "breathe",
    "breed", "brick", "bridge", "brief", "bright", "brilliant", "bring",
    "broad", "broadcast", "broken", "brother", "brown", "brush", "bubble",
    "budget", "build", "building", "bullet", "bunch", "burden", "burn",
    "burst", "bus", "bush", "business", "busy", "but", "butter", "button",
    "buy", "by",
    "cabin", "cable", "cake", "calculate", "call", "calm", "camera",
    "camp", "campaign", "campus", "canal", "cancel", "candidate", "capable",
    "capacity", "capital", "capture", "carbon", "care", "career", "careful",
    "carefully", "careless", "carpet", "carry", "case", "cash", "cast",
    "castle", "casual",     "cat", "catch", "category", "cattle", "cause", "ceiling",
    "dog", "sat", "run", "ran", "sit", "bed", "big", "hot", "red",
    "celebrate", "celebration", "cell", "cent", "central", "centre", "century",
    "ceremony", "certain", "certainly", "chain", "chair", "chairman",
    "challenge", "champion", "chance", "change", "channel", "chapter",
    "character", "characteristic", "charge", "charity", "chart", "chase",
    "cheap", "cheat", "check", "cheek", "cheer", "cheese", "chemical",
    "chest", "chicken", "chief", "child", "childhood", "chip", "chocolate",
    "choice", "choose", "church", "cigarette", "circle", "circumstance",
    "citizen", "city", "civil", "claim", "class", "classic", "classroom",
    "clean", "clear", "clearly", "clerk", "clever", "client", "climate",
    "climb", "clock", "close", "closely", "closed", "cloth", "clothes",
    "clothing", "cloud", "club", "coal", "coast", "coat", "code", "coffee",
    "coin", "cold", "collapse", "colleague", "collect", "collection",
    "college", "colour", "column", "combine", "come", "comfort",
    "comfortable", "command", "comment", "commerce", "commercial", "commission",
    "commit", "commitment", "committee", "common", "commonly", "communicate",
    "communication", "community", "company", "compare", "comparison",
    "compete", "competition", "competitive", "complain", "complaint",
    "complete", "completely", "complex", "complicate", "component", "compose",
    "composition", "comprehensive", "computer", "concern", "concerned",
    "condition", "conduct", "conference", "confidence", "confident",
    "confirm", "conflict", "confuse", "confusion", "congress", "connect",
    "connection", "conscious", "consequence", "conservative", "consider",
    "considerable", "consideration", "consist", "consistent", "constant",
    "constantly", "constitute", "construct", "construction", "consult",
    "consumer", "contact", "contain", "contemporary", "content", "contest",
    "context", "continent", "continue", "continuous", "contract", "contrast",
    "contribute", "contribution", "control", "controversial", "convention",
    "conventional", "conversation", "convert", "conviction", "convince",
    "cook", "cooker", "cooking", "cool", "cope", "copy", "core", "corner",
    "corporate", "correct", "correction", "correctly", "cost", "cotton",
    "council", "count", "counter", "country", "county", "couple", "courage",
    "course", "court", "cousin", "cover", "covered", "crack", "craft",
    "crash", "crazy", "cream", "create", "creation", "creative", "creature",
    "credit", "crew", "crime", "criminal", "crisis", "criteria", "criterion",
    "critic", "critical", "criticism", "criticize", "crop", "cross",
    "crowd", "crucial", "cry", "cultural", "culture", "cup", "cure",
    "curious", "currency", "current", "currently", "curtain", "curve",
    "custom", "customer", "cut", "cycle",
    "damage", "dance", "danger", "dangerous", "dare", "dark", "darkness",
    "data", "database", "date", "daughter", "day", "dead", "deaf",
    "deal", "dealer", "dear", "death", "debate", "debt", "decade",
    "decide", "decision", "declare", "decline", "decorate", "decrease",
    "deep", "deeply", "deer", "defeat", "defence", "defend", "defendant",
    "defense", "define", "definite", "definitely", "definition", "degree",
    "delay", "deliberate", "delicate", "deliver", "delivery", "demand",
    "democracy", "demonstrate", "demonstration", "deny", "department",
    "departure", "depend", "dependent", "deposit", "depress", "depression",
    "depth", "deputy", "derive", "describe", "description", "desert",
    "deserve", "design", "designer", "desire", "desk", "desperate", "despite",
    "destination", "destroy", "destruction", "detail", "detailed", "detect",
    "determination", "determine", "develop", "development", "device",
    "diagram", "dialogue", "diamond", "diary", "dictate", "diet", "differ",
    "difference", "different", "difficult", "difficulty", "dig", "dinner",
    "direct", "direction", "directly", "director", "dirty", "disabled",
    "disadvantage", "disagree", "disappear", "disappoint", "disaster",
    "disc", "discipline", "discount", "discover", "discovery", "discrimination",
    "discuss", "discussion", "disease", "dish", "dismiss", "display",
    "dispute", "distance", "distant", "distinction", "distinguish", "distribute",
    "distribution", "district", "disturb", "diverse", "diversity", "divide",
    "division", "divorce", "document", "dog", "dollar", "domestic",
    "dominant", "dominate", "door", "double", "doubt", "down", "download",
    "downstairs", "downtown", "dozen", "draft", "drag", "drama", "dramatic",
    "dramatically", "draw", "drawing", "dream", "dress", "drink", "drive",
    "driver", "drop", "drug", "drunk", "dry", "due", "dull", "dump",
    "during", "dust", "duty",
    "each", "eager", "ear", "early", "earn", "earnings", "earth", "ease",
    "east", "eastern", "easy", "eat", "echo", "ecology", "economic",
    "economics", "economy", "edge", "edition", "editor", "educate",
    "education", "educational", "effect", "effective", "effectively",
    "efficiency", "efficient", "effort", "egg", "elaborate", "elbow",
    "elderly", "elect", "election", "electric", "electricity", "electronic",
    "element", "eliminate", "else", "elsewhere", "emerge", "emergency",
    "emission", "emotion", "emotional", "emphasis", "emphasize", "empire",
    "employ", "employee", "employer", "employment", "empty", "enable",
    "encounter", "encourage", "encouragement", "end", "ending", "enemy",
    "energy", "enforce", "engage", "engine", "engineer", "engineering",
    "enjoy", "enjoyment", "enormous", "enough", "ensure", "enter", "enterprise",
    "entertain", "entertainment", "enthusiasm", "enthusiastic", "entire",
    "entirely", "entrance", "entry", "envelope", "environment",
    "environmental", "episode", "equal", "equally", "equipment", "era",
    "error", "escape", "especially", "essay", "essential", "essentially",
    "establish", "establishment", "estate", "estimate", "ethnic", "evaluate",
    "evaluation", "even", "evening", "event", "eventually", "ever", "every",
    "everybody", "everyday", "everyone", "everything", "everywhere",
    "evidence", "evident", "evil", "evolution", "evolve", "exact", "exactly",
    "examination", "examine", "example", "exceed", "excellent", "except",
    "exception", "excess", "exchange", "excite", "excitement", "exciting",
    "exclude", "exclusive", "excuse", "execute", "executive", "exercise",
    "exhibit", "exhibition", "exist", "existence", "existing", "exit",
    "expand", "expansion", "expect", "expectation", "expense", "expensive",
    "experience", "experiment", "experimental", "expert", "expertise",
    "explain", "explanation", "explicit", "exploit", "exploration", "explore",
    "explosion", "export", "expose", "exposure", "express", "expression",
    "extend", "extension", "extensive", "extent", "external", "extra",
    "extraordinary", "extreme", "extremely", "eye",
    "fabric", "face", "facility", "fact", "factor", "factory", "faculty",
    "fail", "failure", "fair", "fairly", "fairness", "faith", "faithful",
    "fall", "false", "familiar", "family", "famous", "fan", "fantastic",
    "far", "farm", "farmer", "farming", "fascinating", "fashion", "fast",
    "fasten", "fat", "father", "fault", "favour", "favourable", "favourite",
    "fear", "feather", "feature", "federal", "fee", "feed", "feedback",
    "feel", "feeling", "fellow", "female", "fence", "festival", "fever",
    "few", "fewer", "fibre", "fiction", "field", "fierce", "fifteen", "fifth",
    "fifty", "fight", "fighter", "figure", "file", "fill", "film",
    "filter", "final", "finally", "finance", "financial", "find", "finding",
    "fine", "finger", "finish", "fire", "firm", "firmly", "first",
    "fish", "fishing", "fit", "fitness", "fix", "fixed", "flag", "flame",
    "flat", "flavour", "flesh", "flexible", "flight", "flood", "floor",
    "flow", "flower", "fly", "focus", "folk", "follow", "following",
    "food", "foot", "football", "for", "force", "forecast", "foreign",
    "foreigner", "forest", "forever", "forget", "forgive", "fork", "form",
    "formal", "format", "formation", "former", "formula", "forth", "fortunate",
    "fortune", "forward", "found", "foundation", "founder", "four",
    "frame", "framework", "free", "freedom", "freeze", "freight", "frequency",
    "frequent", "frequently", "fresh", "friend", "friendly", "friendship",
    "front", "frozen", "fruit", "fuel", "fulfil", "full", "fully", "fun",
    "function", "fund", "fundamental", "funding", "funeral", "funny", "fur",
    "furniture", "further", "furthermore", "future",
    "gain", "gallery", "game", "gang", "gap", "garage", "garden", "gas",
    "gate", "gather", "gay", "gaze", "gear", "gender", "gene", "general",
    "generally", "generate", "generation", "generous", "genetic", "genius",
    "gentle", "gentleman", "genuine", "gesture", "get", "giant", "gift",
    "girl", "girlfriend", "give", "given", "glad", "glance", "glass",
    "global", "glove", "goal", "god", "gold", "golden", "golf", "good",
    "goods", "govern", "government", "governor", "grab", "grace", "grade",
    "gradually", "grain", "grand", "grandfather", "grandmother", "grant",
    "grass", "grateful", "grave", "great", "greatly", "green", "greet",
    "grey", "ground", "group", "grow", "growth", "guarantee", "guard",
    "guess", "guest", "guide", "guilty", "gun", "gut",
    "habit", "habitat", "hair", "half", "hall", "hand", "handle", "hang",
    "happen", "happiness", "happy", "harbour", "hard", "hardly", "harm",
    "harmful", "harmony", "harsh", "harvest", "hat", "hate", "hatred",
    "have", "head", "headline", "headquarters", "health", "healthy", "hear",
    "hearing", "heart", "heat", "heating", "heaven", "heavy", "height",
    "help", "helpful", "hence", "heritage", "hero", "hide", "high",
    "highlight", "highly", "highway", "hill", "hire", "historic", "historical",
    "history", "hit", "hobby", "hold", "hole", "holiday", "hollow", "holy",
    "home", "honest", "honesty", "honour", "hook", "hope", "horizon",
    "horrible", "horror", "horse", "hospital", "host", "hot", "hotel",
    "hour", "house", "household", "housing", "huge", "human", "humour",
    "hundred", "hunger", "hungry", "hunt", "hunting", "hurt", "husband",
    "hypothesis",
    "ice", "icon", "idea", "ideal", "identical", "identify", "identity",
    "ignore", "illegal", "illness", "illustrate", "image", "imagination",
    "imagine", "immediate", "immediately", "immense", "immigrant",
    "immigration", "impact", "implement", "implication", "imply", "import",
    "importance", "important", "impose", "impossible", "impress", "impression",
    "impressive", "improve", "improvement", "incentive", "inch", "incident",
    "include", "including", "income", "incorporate", "increase", "increased",
    "increasing", "increasingly", "incredible", "indeed", "independence",
    "independent", "index", "indicate", "indication", "individual",
    "industrial", "industry", "inevitable", "infant", "infection", "inflation",
    "influence", "influential", "inform", "informal", "information",
    "infrastructure", "ingredient", "initial", "initially", "initiative",
    "injection", "injure", "injury", "inner", "innocent", "innovation",
    "innovative", "input", "inquiry", "insect", "insert", "inside", "insight",
    "insist", "inspect", "inspection", "inspector", "inspiration", "inspire",
    "install", "installation", "instance", "instant", "instantly", "instead",
    "instinct", "institute", "institution", "institutional", "instruction",
    "instructor", "instrument", "insurance", "intellectual", "intelligence",
    "intelligent", "intend", "intense", "intensity", "intention", "interact",
    "interaction", "interest", "interested", "interesting", "internal",
    "international", "internet", "interpret", "interpretation", "intervention",
    "interview", "intimate", "introduce", "introduction", "invade", "invasion",
    "invent", "invention", "invest", "investigate", "investigation",
    "investment", "investor", "invitation", "invite", "involve", "involved",
    "involvement", "iron", "island", "isolate", "isolation", "issue", "item",
    "itself",
    "jacket", "jail", "jam", "jet", "jewellery", "job", "join",
    "joint", "joke", "journal", "journalist", "journey", "joy", "judge",
    "judgment", "juice", "jump", "junction", "junior", "jury", "justice",
    "justify",
    "keen", "keep", "key", "keyboard", "kick", "kid", "kill", "killer",
    "kind", "king", "kingdom", "kiss", "kit", "kitchen", "knee", "knife",
    "knock", "know", "knowledge",
    "lab", "label", "laboratory", "labour", "lack", "ladder", "lady",
    "lake", "lamp", "land", "landing", "landlord", "landscape", "lane",
    "language", "lap", "large", "largely", "laser", "last", "late", "later",
    "latter", "laugh", "laughter", "launch", "law", "lawn", "lawsuit",
    "lawyer", "lay", "layer", "layout", "lazy", "lead", "leader", "leadership",
    "leading", "leaf", "league", "lean", "leap", "learn", "learning",
    "least", "leather", "leave", "lecture", "left", "leg", "legacy",
    "legal", "legend", "legislation", "legitimate", "leisure", "lemon",
    "lend", "length", "lesson", "let", "letter", "level", "liable",
    "liberal", "library", "licence", "lid", "lie", "life", "lifestyle",
    "lifetime", "lift", "light", "lightly", "like", "likelihood", "likely",
    "likewise", "limb", "limit", "limitation", "limited", "line", "link",
    "lion", "lip", "liquid", "list", "listen", "listener", "literally",
    "literary", "literature", "litre", "little", "live", "lively", "living",
    "load", "loan", "lobby", "local", "locate", "location", "lock", "log",
    "logic", "logical", "lonely", "long", "look", "loop", "loose",
    "lord", "lose", "loss", "lost", "lot", "loud", "love", "lovely",
    "lover", "low", "lower", "luck", "lucky", "lunch", "lung",
    "machine", "machinery", "mad", "magazine", "magic", "main", "mainly",
    "maintain", "maintenance", "major", "majority", "make", "maker", "makeup",
    "male", "mall", "management", "manager", "manner", "manufacturer",
    "manufacturing", "map", "march", "margin", "mark", "marker", "market",
    "marketing", "marriage", "married", "marry", "mask", "mass", "massive",
    "master", "match", "mate", "material", "maths", "matter", "mature",
    "maximum", "mayor", "meal", "mean", "meaning", "meaningful", "means",
    "meantime", "meanwhile", "measure", "measurement", "meat", "mechanic",
    "mechanical", "mechanism", "medal", "media", "medical", "medication",
    "medicine", "medium", "meet", "meeting", "member", "membership",
    "memory", "mental", "mention", "menu", "merchant", "mercy", "merely",
    "merger", "merit", "mess", "message", "metal", "method", "metre",
    "middle", "midnight", "might", "mild", "mile", "milk", "mill",
    "mind", "mine", "mineral", "minimum", "mining", "minister", "ministry",
    "minor", "minority", "minute", "miracle", "mirror", "miss", "missile",
    "missing", "mission", "mistake", "mix", "mixed", "mixture", "mobile",
    "mode", "model", "moderate", "modern", "modest", "modify", "module",
    "mom", "moment", "monitor", "month", "monument", "mood", "moon",
    "moral", "more", "moreover", "morning", "mortgage", "most", "mostly",
    "mother", "motion", "motivate", "motivation", "motor", "mount",
    "mountain", "mouse", "mouth", "move", "movement", "movie", "much",
    "multiple", "murder", "muscle", "museum", "music", "musical", "musician",
    "mutual", "mystery",
    "narrow", "nation", "national", "nationality", "native", "natural",
    "naturally", "nature", "naval", "near", "nearby", "nearly", "neat",
    "necessarily", "necessary", "necessity", "neck", "need", "needle",
    "negative", "negotiate", "negotiation", "neighbour", "neighbourhood",
    "neither", "nerve", "nervous", "net", "network", "neutral", "never",
    "nevertheless", "new", "newly", "news", "newspaper", "next", "nice",
    "night", "noise", "noisy", "none", "nonsense", "normal", "normally",
    "north", "northern", "nose", "notable", "note", "notebook", "nothing",
    "notice", "notion", "novel", "now", "nowhere", "nuclear", "number",
    "numerous", "nurse", "nursery",
    "obey", "object", "objection", "objective", "obligation", "observation",
    "observe", "observer", "obstacle", "obtain", "obvious", "obviously",
    "occasion", "occasional", "occasionally", "occupation", "occupy", "occur",
    "ocean", "odd", "offence", "offend", "offensive", "offer", "office",
    "officer", "official", "often", "oil", "okay", "old", "ongoing",
    "online", "only", "open", "opening", "openly", "operate", "operation",
    "operator", "opinion", "opponent", "opportunity", "oppose", "opposite",
    "opposition", "option", "oral", "orbit", "order", "ordinary", "organ",
    "organic", "organisation", "organise", "organization", "organize",
    "orientation", "origin", "original", "originally", "other", "otherwise",
    "outcome", "outdoor", "outer", "outlet", "outline", "outlook", "output",
    "outside", "outstanding", "overcome", "overlook", "overnight", "overseas",
    "overview", "owe", "own", "owner", "ownership", "oxygen",
    "pace", "pack", "package", "packet", "page", "pain", "painful",
    "paint", "painter", "painting", "pair", "palace", "pale", "palm",
    "pan", "panel", "panic", "pants", "paper", "parade", "paragraph",
    "parallel", "parent", "park", "parking", "parliament", "part",
    "participant", "participate", "participation", "particular", "particularly",
    "partly", "partner", "partnership", "party", "pass", "passage",
    "passenger", "passion", "passive", "password", "past", "path", "patience",
    "patient", "pattern", "pause", "pay", "payment", "peace", "peaceful",
    "peak", "penalty", "pension", "people", "perceive", "percentage",
    "perception", "perfect", "perfectly", "perform", "performance", "performer",
    "period", "permanent", "permission", "permit", "person", "personal",
    "personality", "personally", "personnel", "perspective", "persuade",
    "pet", "phase", "phenomenon", "philosophy", "phone", "photo",
    "photograph", "photographer", "photography", "phrase", "physical",
    "physically", "physics", "piano", "pick", "picture", "piece", "pig",
    "pile", "pilot", "pin", "pipe", "pitch", "pity", "place", "plain",
    "plan", "plane", "planet", "planning", "plant", "plastic", "plate",
    "platform", "play", "player", "pleasure", "plenty", "plot", "plug",
    "plus", "pocket", "poem", "poet", "poetry", "point", "poison",
    "police", "policeman", "policy", "political", "politician", "politics",
    "poll", "pollution", "pool", "poor", "pop", "popular", "popularity",
    "population", "port", "portfolio", "portion", "portrait", "pose",
    "position", "positive", "possess", "possession", "possibility", "possible",
    "possibly", "post", "poster", "pot", "potato", "potential", "potentially",
    "pound", "pour", "poverty", "powder", "power", "powerful", "practical",
    "practice", "practise", "praise", "pray", "prayer", "precise", "precisely",
    "predict", "prediction", "prefer", "preference", "pregnant", "premise",
    "premium", "preparation", "prepare", "prescription", "presence", "present",
    "presentation", "preserve", "president", "press", "pressure", "presume",
    "pretend", "pretty", "prevent", "prevention", "previous", "previously",
    "price", "pride", "priest", "primarily", "primary", "prime", "prince",
    "princess", "principal", "principle", "print", "printer", "prior",
    "priority", "prison", "prisoner", "privacy", "private", "privilege",
    "prize", "probability", "probably", "probe", "problem", "procedure",
    "proceed", "proceeding", "process", "produce", "producer", "product",
    "production", "productive", "productivity", "profession", "professional",
    "professor", "profile", "profit", "program", "programme", "progress",
    "project", "promise", "promote", "promotion", "prompt", "proof",
    "proper", "properly", "property", "proportion", "proposal", "propose",
    "proposed", "prospect", "protect", "protection", "protective", "protein",
    "protest", "proud", "prove", "provide", "provider", "province",
    "provision", "psychological", "psychology", "pub", "public",
    "publication", "publicity", "publish", "publisher", "pull", "punch",
    "punishment", "pupil", "purchase", "pure", "purpose", "pursue",
    "push", "put",
    "qualification", "qualified", "qualify", "quality", "quantity", "quarter",
    "queen", "query", "quest", "question", "queue", "quick", "quickly",
    "quiet", "quietly", "quit", "quite", "quote",
    "race", "racial", "radical", "radio", "rail", "railway", "rain",
    "raise", "range", "rank", "rapid", "rapidly", "rare", "rarely",
    "rate", "rather", "rating", "ratio", "raw", "reach", "react",
    "reaction", "read", "reader", "reading", "ready", "real", "realise",
    "realistic", "reality", "realize", "really", "reason", "reasonable",
    "recall", "receipt", "receive", "receiver", "recent", "recently",
    "reception", "recipe", "recognition", "recognise", "recognize",
    "recommend", "recommendation", "record", "recording", "recover",
    "recovery", "recruit", "recruitment", "red", "reduce", "reduction",
    "refer", "reference", "reflect", "reflection", "reform", "refresh",
    "refugee", "refuse", "regard", "regarding", "regardless", "regime",
    "region", "regional", "register", "registration", "regret", "regular",
    "regularly", "regulate", "regulation", "reject", "rejection", "relate",
    "relation", "relationship", "relative", "relatively", "relax", "release",
    "relevant", "relief", "religion", "religious", "reluctant", "rely",
    "remain", "remaining", "remark", "remarkable", "remedy", "remember",
    "remind", "remote", "removal", "remove", "render", "rent", "rental",
    "repair", "repeat", "repeatedly", "replace", "replacement", "reply",
    "report", "reporter", "represent", "representation", "representative",
    "reputation", "request", "require", "requirement", "rescue", "research",
    "researcher", "reservation", "reserve", "residence", "resident",
    "residential", "resign", "resist", "resistance", "resolution", "resolve",
    "resort", "resource", "respect", "respond", "respondent", "response",
    "responsibility", "responsible", "rest", "restaurant", "restoration",
    "restore", "restrict", "restriction", "result", "retail", "retailer",
    "retain", "retire", "retirement", "return", "reveal", "revenue",
    "reverse", "review", "revolution", "revolutionary", "reward", "rhythm",
    "rice", "rich", "rid", "ride", "rifle", "right", "ring", "riot",
    "rise", "risk", "risky", "ritual", "rival", "river", "road", "rock",
    "role", "roll", "romantic", "roof", "room", "root", "rope", "rough",
    "roughly", "round", "route", "routine", "row", "royal", "rule",
    "ruler", "running", "rural",
    "sacrifice", "sad", "sadly", "safe", "safely", "safety", "sail",
    "sailor", "salad", "salary", "sale", "salt", "same", "sample", "sanction",
    "sand", "satellite", "satisfaction", "satisfied", "satisfy", "sauce",
    "save", "saving", "scale", "scan", "scene", "schedule", "scheme",
    "scholar", "scholarship", "school", "science", "scientific", "scientist",
    "scope", "score", "scream", "screen", "script", "sea", "search",
    "season", "seat", "second", "secondary", "secret", "secretary", "section",
    "sector", "secure", "security", "seed", "seek", "select", "selection",
    "self", "seller", "senate", "senator", "send", "senior", "sense",
    "sensible", "sensitive", "sentence", "separate", "separation", "sequence",
    "serial", "series", "serious", "seriously", "servant", "serve", "service",
    "session", "set", "setting", "settle", "settlement", "setup", "severe",
    "severely", "sex", "sexual", "shade", "shadow", "shake", "shall",
    "shame", "shape", "share", "sharp", "sharply", "sheet", "shelf",
    "shell", "shelter", "shift", "shine", "ship", "shirt", "shock",
    "shoe", "shoot", "shop", "shopping", "shore", "short", "shortly",
    "shot", "shoulder", "shout", "show", "shower", "shut", "sick",
    "side", "sight", "sign", "signal", "signature", "significance",
    "significant", "significantly", "silence", "silent", "silver", "similar",
    "similarly", "simple", "simply", "simulation", "sin", "sing", "singer",
    "single", "sink", "sir", "sister", "site", "situation", "size",
    "skill", "skilled", "skin", "skirt", "sky", "slave", "sleep", "slice",
    "slide", "slight", "slightly", "slip", "slow", "slowly", "small",
    "smart", "smell", "smile", "smoke", "smooth", "snap", "snow", "soak",
    "social", "society", "soft", "software", "soil", "solar", "soldier",
    "sole", "solid", "solution", "solve", "somebody", "somehow", "someone",
    "something", "sometimes", "somewhat", "son", "song", "soon", "sophisticated",
    "sorry", "sort", "soul", "sound", "source", "south", "southern",
    "space", "span", "spare", "spatial", "speak", "speaker", "special",
    "specialist", "specialize", "species", "specific", "specifically",
    "specify", "speech", "speed", "spell", "spend", "spending", "spin",
    "spirit", "spiritual", "spite", "split", "spokesman", "sponsor",
    "sport", "spot", "spread", "spring", "square", "stable", "stadium",
    "staff", "stage", "stair", "stake", "stamp", "stand", "standard",
    "standing", "star", "stare", "start", "state", "statement", "station",
    "statistic", "status", "statute", "stay", "steady", "steal", "steel",
    "steep", "stem", "step", "stick", "stiff", "still", "stock", "stomach",
    "stone", "stop", "storage", "store", "storm", "story", "straight",
    "strange", "stranger", "strategic", "strategy", "stream", "street",
    "strength", "strengthen", "stress", "stretch", "strict", "strike",
    "string", "strip", "stroke", "strong", "strongly", "structure",
    "struggle", "student", "studio", "study", "stuff", "style", "subject",
    "submit", "subsequent", "substance", "substantial", "substitute",
    "subtle", "suburb", "succeed", "success", "successful", "successfully",
    "such", "sudden", "suddenly", "suffer", "suffering", "sufficient",
    "sufficiently", "sugar", "suggest", "suggestion", "suit", "suitable",
    "suite", "sum", "summarize", "summary", "summer", "sun", "super",
    "superior", "supermarket", "supply", "support", "supporter", "supportive",
    "suppose", "sure", "surely", "surface", "surgery", "surprise",
    "surprised", "surprising", "surprisingly", "surround", "surrounding",
    "survey", "survival", "survive", "survivor", "suspect", "suspend",
    "suspicion", "sustain", "sustainable", "swallow", "swear", "sweep",
    "sweet", "swim", "swing", "switch", "symbol", "sympathy", "symptom",
    "syndrome", "synthetic", "system", "systematic",
    "table", "tablet", "tackle", "tail", "take", "tale", "talent",
    "talented", "talk", "tank", "tap", "tape", "target", "task", "taste",
    "tax", "taxpayer", "tea", "teach", "teacher", "teaching", "team",
    "tear", "technical", "technique", "technological", "technology",
    "telephone", "television", "tell", "temperature", "temple", "temporary",
    "tend", "tendency", "tennis", "tension", "tent", "term", "terminal",
    "terms", "terrain", "terrible", "territory", "terror", "terrorism",
    "terrorist", "test", "testify", "testimony", "testing", "text",
    "texture", "thanks", "theme", "theory", "therapist", "therapy",
    "therefore", "thesis", "thick", "thickness", "thief", "thing", "think",
    "thinking", "third", "thirsty", "thorough", "thought", "thousand",
    "threat", "threaten", "thriller", "throat", "through", "throughout",
    "throw", "thumb", "ticket", "tide", "tie", "tight", "till",
    "timber", "tissue", "title", "tobacco", "today", "toe", "together",
    "tolerance", "tolerate", "tomorrow", "tone", "tongue", "tool", "tooth",
    "topic", "total", "totally", "touch", "tough", "tour", "tourism",
    "tourist", "tournament", "toward", "towards", "tower", "town", "toxic",
    "trace", "track", "trade", "trading", "tradition", "traditional",
    "traffic", "tragedy", "tragic", "trail", "train", "training", "trait",
    "transaction", "transfer", "transform", "transformation", "transition",
    "translate", "translation", "transmission", "transmit", "transparent",
    "transport", "transportation", "trap", "trash", "travel", "traveller",
    "treasure", "treat", "treatment", "treaty", "tree", "tremendous",
    "trend", "trial", "triangle", "tribe", "trick", "trigger", "trip",
    "troop", "trophy", "trouble", "troubled", "truck", "truly", "trunk",
    "trust", "truth", "try", "tube", "tuck", "tune", "tunnel",
    "turn", "twice", "twin", "twist", "type", "typical", "typically",
    "ugly", "ultimate", "ultimately", "umbrella", "unable", "unanimous",
    "uncle", "under", "undergo", "undergraduate", "underground",
    "underlying", "undermine", "understand", "understanding", "undertake",
    "undertaking", "unemployed", "unemployment", "unexpected", "unfair",
    "unfortunate", "unhappy", "uniform", "union", "unique", "unit",
    "unite", "united", "unity", "universal", "universe", "university",
    "unknown", "unless", "unlike", "unlikely", "unnecessary", "unpleasant",
    "unusual", "update", "upon", "upper", "upset", "urban",
    "urge", "urgent", "usage", "useful", "useless", "user", "usual",
    "usually", "utility",
    "vacation", "valid", "validity", "valley", "valuable", "value",
    "van", "variable", "variation", "variety", "various", "vary", "vast",
    "vehicle", "venture", "version", "vertical", "vessel", "veteran",
    "via", "victim", "victory", "video", "view", "viewer", "village",
    "violate", "violation", "violence", "violent", "virtually", "virtue",
    "virus", "visible", "vision", "visit", "visitor", "visual", "vital",
    "vitamin", "vocal", "voice", "volume", "voluntary", "volunteer", "vote",
    "voter",
    "wage", "wait", "wake", "walk", "wall", "wander", "want", "war",
    "ward", "warm", "warmth", "warn", "warning", "wash", "waste",
    "watch", "water", "wave", "weak", "weaken", "weakness", "wealth",
    "wealthy", "weapon", "wear", "weather", "web", "website", "wedding",
    "week", "weekend", "weekly", "weight", "welcome", "welfare", "well",
    "west", "western", "wet", "whale", "wheel", "whereas", "whether",
    "which", "while", "whilst", "white", "whole", "wholly", "wide",
    "widely", "widespread", "width", "wife", "wild", "wildlife", "will",
    "willing", "win", "wind", "window", "wine", "wing", "winner",
    "winter", "wire", "wisdom", "wise", "wish", "wit", "withdraw",
    "withdrawal", "within", "without", "witness", "woman", "wonder",
    "wonderful", "wood", "wooden", "word", "work", "worker", "workforce",
    "working", "works", "workshop", "world", "worldwide", "worm", "worried",
    "worry", "worse", "worship", "worst", "worth", "worthwhile", "worthy",
    "wound", "wrap", "wrist", "writer", "writing", "wrong",
    "yard", "year", "yell", "yellow", "yesterday", "yield", "young",
    "youth",
    "zero", "zone",
}

COMMON_ENGLISH_WORDS.update({
    "the", "be", "that", "you", "do", "this", "say", "an", "one", "would",
    "there", "what", "who", "go", "when", "can", "time", "just", "some",
    "could", "see", "than", "then", "use", "two", "how", "way", "these",
    "were", "been", "has", "had", "did", "does", "done", "many", "too",
    "very", "maybe", "perhaps", "though", "since", "until", "once",
    "or", "to", "from", "i", "am", "my", "your", "he", "she", "it", "we",
    "they", "me", "him", "her", "us", "them", "his", "its", "our", "their",
    "mine", "yours", "hers", "ours", "theirs", "not", "no", "nor", "but",
    "if", "because", "so", "yet", "for", "as", "at", "by", "of", "on",
    "up", "down", "in", "out", "off", "over", "under", "with", "into",
    "through", "during", "before", "after", "above", "below", "between",
    "about", "across", "along", "among", "around", "behind", "beyond",
    "inside", "near", "onto", "outside", "past", "toward", "towards",
    "upon", "within", "without", "madam", "sir", "dear", "disappointment",
    "disappointed", "disappointing", "purchase", "purchased", "purchasing",
    "regret", "regrets", "regretted", "kindly", "faithfully", "sincerely",
    "yours", "please", "thank", "thanks", "grateful", "appreciate",
    "apologise", "apologize", "apology", "complaint", "complain", "complained",
    "replacement", "refund", "damage", "damaged", "delivery", "delivered",
    "parcel", "package", "receipt", "invoice", "order", "ordered", "arrange",
    "arranged", "arrangement", "convenient", "convenience", "earliest",
    "possible", "kindly", "prompt", "resolution", "enquire", "enquiry",
    "inquire", "inquiry", "regarding", "response", "respond", "customer",
    "service", "quality", "product", "online", "website", "store", "item",
    "items", "condition", "receive", "received", "enclose", "enclosed",
    "photograph", "photographs", "photo", "photos", "copy", "copies",
})

ADVANCED_VOCAB = {
    "abundant", "accommodate", "accomplish", "acquire", "adequate", "advocate",
    "alleviate", "ambiguous", "anticipate", "apprehensive", "articulate",
    "augment", "benevolent", "cacophony", "capacious", "collaborate",
    "comprehensive", "conundrum", "contemplate", "contend", "conundrum",
    "convey", "culminate", "debilitate", "deliberate", "delineate",
    "detrimental", "diminutive", "disseminate", "elaborate", "elicit",
    "emancipate", "encompass", "endorse", "exacerbate", "exemplify",
    "facilitate", "fluctuate", "formidable", "harbinger", "implement",
    "inadvertent", "incongruous", "indigenous", "indispensable", "integrate",
    "juxtaposition", "meticulous", "mitigate", "negate", "notorious",
    "obscure", "paradigm", "perpetuate", "pragmatic", "profound",
    "propagate", "quintessential", "reconcile", "relegate", "scrutinize",
    "solicit", "substantiate", "succinct", "superfluous", "tangible",
    "tenacious", "ubiquitous", "viable", "volatile", "warrant",
    "prevalent", "catalyst", "dichotomy", "empirical", "extraneous",
    "impede", "intrinsic", "malleable", "nuance", "ostracize",
    "pertinent", "resilient", "salient", "transcend", "unprecedented",
    "versatile", "aesthetic", "benevolent", "consecutive", "detrimental",
    "efficacious", "gratify", "heterogeneous", "implication", "legitimate",
    "mandate", "optimization", "paramount", "repercussion", "subsequent",
    "terminology", "vindicate", "widespread", "acknowledge", "assess",
    "attribute", "coherent", "consequence", "demonstrate", "enhance",
    "fundamental", "illustrate", "methodology", "perspective", "phenomenon",
    "significant", "theoretical", "vary", "complement", "constitute",
    "derive", "distinct", "evaluate", "inevitable", "predominant",
    "principal", "relevant", "sufficient", "transform", "undertake",
    "abstract", "accumulate", "allocate", "approximate", "circumstance",
    "component", "controversial", "correspond", "criteria", "deviate",
    "dominate", "emerge", "emphasize", "exclude", "exploit", "generate",
    "hypothesis", "identify", "indicate", "investigate", "manifest",
    "modify", "necessitate", "parallel", "perceive", "proportion",
    "regulate", "stimulate", "submit", "terminate", "validate",
    "expanded", "relocated", "resurfaced", "constructed", "modernised",
    "renovated", "redesigned", "rebuilt", "redeveloped", "enlarged",
    "widened", "converted", "transformed", "replaced", "relocated",
    "extended", "installed", "introduced", "removed", "demolished",
    "altered", "modified", "approximately", "dramatically", "significantly",
    "substantially", "considerably", "remarkably", "noticeably", "gradually",
    "steadily", "spacious", "modest", "adjacent", "nearby", "surrounding",
    "central", "located", "situated", "comprising", "consisting", "featuring",
    "housing", "containing", "whereas", "while", "although", "compared",
    "relative", "contrast", "differ", "different", "similarly", "likewise",
    "substantial", "remarkable", "noticeable", "considerable", "dramatic",
    "significant", "evident", "apparent", "clear", "obvious", "exceeded",
    "surpassed", "grew", "increased", "decreased", "declined", "rose",
    "fell", "construction", "development", "expansion", "improvement",
    "modernisation", "redevelopment", "relocation", "introduction",
    "extension", "expansion", "facility", "infrastructure",
    "accommodate", "serve", "provide", "contain", "consist",
    "previously", "originally", "currently", "subsequently", "eventually",
    "furthermore", "moreover", "nevertheless", "accordingly",
    "consequently", "therefore", "specifically", "particularly",
    "southern", "northern", "eastern", "western", "central",
    "boundary", "entrance", "surrounded", "connected", "located",
    "designed", "constructed", "developed", "established", "created",
    "offered", "housed", "featured", "included", "comprised",
    "expanding", "relocating", "constructing", "modernising",
    "renovating", "rebuilding", "redeveloping", "extending",
    "underwent", "accommodated", "enrolment", "quadrupled",
    "tripled", "doubled", "halved", "percentage", "proportion",
    "peak", "peaked", "fluctuation", "fluctuate", "fluctuated",
    "stood", "accounted", "represented", "respectively",
    "slight", "slightly", "minimal", "minimally", "rapid",
    "rapidly", "sharp", "sharply", "twofold", "threefold",
    "greater", "larger", "smaller", "higher", "lower", "fewer",
    "exceeding", "surpassing", "approaching", "numbering",
    "totalling", "amounting", "comprised", "consisting",
    "measured", "estimated", "calculated", "projected",
    "outstripped", "overtook", "surpassed", "exceeded",
    "remained", "stayed", "unchanged", "levelled", "stabilised",
    "plateaued", "fluctuating", "rising", "falling", "growing",
    "declining", "increasing", "decreasing", "dropping",
    "climbing", "soaring", "plunging", "plummeting", "surged",
    "soared", "plunged", "plummeted", "surged",
}

TRANSITION_WORDS = {
    "however", "moreover", "furthermore", "additionally", "consequently",
    "therefore", "nevertheless", "nonetheless", "alternatively",
    "conversely", "in contrast", "on the other hand", "in addition",
    "as a result", "for instance", "for example", "in conclusion",
    "to summarize", "firstly", "secondly", "thirdly", "finally",
    "subsequently", "meanwhile", "simultaneously", "otherwise",
    "thus", "hence", "indeed", "specifically", "in particular",
    "accordingly", "evidently", "obviously", "clearly",
}


class VocabularyAnalyzer:
    @staticmethod
    def analyze(text: str) -> dict:
        words = re.findall(r"\b[a-zA-Z]+\b", text.lower())
        word_count = len(words)
        unique_words = set(words)
        unique_word_count = len(unique_words)

        if word_count == 0:
            return {
                "word_count": 0,
                "unique_word_count": 0,
                "type_token_ratio": 0.0,
                "average_sentence_length": 0.0,
                "sentence_count": 0,
                "advanced_vocab_count": 0,
                "advanced_vocab_percentage": 0.0,
                "repeated_words": [],
                "score": 0.0,
                "real_word_ratio": 0.0,
                "is_gibberish": True,
            }

        KNOWN_WORDS = COMMON_ENGLISH_WORDS | ADVANCED_VOCAB
        VOWELS = set("aeiouy")

        real_words = 0
        suspicious_words = 0
        for w in words:
            if w in KNOWN_WORDS:
                real_words += 1
                continue
            vowel_count = sum(1 for ch in w if ch in VOWELS)
            if vowel_count == 0:
                suspicious_words += 1
                continue
            vowel_ratio = vowel_count / len(w)
            if vowel_ratio < 0.25:
                suspicious_words += 1
                continue
            cons_run = 0
            max_run = 0
            cons_at_end = 0
            for ch in w:
                if ch not in VOWELS:
                    cons_run += 1
                    max_run = max(max_run, cons_run)
                    cons_at_end = cons_run
                else:
                    cons_run = 0
            if max_run > 4:
                suspicious_words += 1
                continue
            if cons_at_end > 3:
                suspicious_words += 1
                continue
            real_words += 1

        real_word_ratio = real_words / word_count if word_count > 0 else 0.0
        is_gibberish = real_word_ratio < 0.50 or (suspicious_words > word_count * 0.3 and real_word_ratio < 0.70)

        type_token_ratio = unique_word_count / word_count if word_count > 0 else 0.0

        sentences = re.split(r"[.!?]+", text)
        sentences = [s.strip() for s in sentences if s.strip()]
        sentence_count = len(sentences)

        avg_sentence_length = word_count / sentence_count if sentence_count > 0 else 0.0

        advanced_found = [w for w in unique_words if w in ADVANCED_VOCAB]
        advanced_count = len(advanced_found)
        advanced_percentage = (advanced_count / unique_word_count * 100) if unique_word_count > 0 else 0.0

        word_freq = Counter(words)
        repeated = [
            {"word": w, "count": c}
            for w, c in word_freq.items()
            if c > 2 and len(w) > 3
        ]

        subordinating = {"because", "although", "while", "whereas", "since",
                         "unless", "despite", "in spite of", "though",
                         "even though", "as", "once", "until", "if", "when",
                         "where", "after", "before"}
        relative = {"which", "that", "who", "whom", "whose", "where", "when"}
        complex_sentences = 0
        for s in sentences:
            lower = s.lower()
            words_in_s = re.findall(r"\b[a-zA-Z]+\b", lower)
            if any(w in subordinating for w in words_in_s):
                complex_sentences += 1
            elif any(w in relative for w in words_in_s):
                complex_sentences += 1
            elif len(words_in_s) > 20:
                complex_sentences += 1

        complexity_ratio = complex_sentences / sentence_count if sentence_count > 0 else 0
        complexity_score = min(complexity_ratio / 0.6 * 20, 20)

        ttr_score = min(type_token_ratio / 0.7 * 15, 15)
        adv_score = min(advanced_percentage / 12 * 45, 45)
        length_score = min(max(0, 15 - abs(avg_sentence_length - 15) * 1.5), 15)
        score = round(ttr_score + adv_score + length_score + complexity_score, 2)

        if is_gibberish:
            penalty = 1.0 - min((0.50 - real_word_ratio) * 3, 0.90)
            score = round(score * penalty, 2)

        return {
            "word_count": word_count,
            "unique_word_count": unique_word_count,
            "type_token_ratio": round(type_token_ratio, 4),
            "average_sentence_length": round(avg_sentence_length, 2),
            "sentence_count": sentence_count,
            "advanced_vocab_count": advanced_count,
            "advanced_vocab_percentage": round(advanced_percentage, 2),
            "repeated_words": repeated,
            "complex_sentence_count": complex_sentences,
            "complexity_ratio": round(complexity_ratio, 4),
            "complexity_score": round(complexity_score, 2),
            "score": score,
            "real_word_ratio": round(real_word_ratio, 4),
            "is_gibberish": is_gibberish,
        }