"""add skill type to reading questions

Revision ID: 0b684a28f562
Revises: 1bef7ca54143
Create Date: 2026-06-23 15:30:59.715217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b684a28f562'
down_revision: Union[str, Sequence[str], None] = '1bef7ca54143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_attempts', sa.Column('skill_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_attempts', 'skill_type')
    # ### end Alembic commands ###
