"""add reading passages, questions, and attempts

Revision ID: 1bef7ca54143
Revises: e5439135ac3a
Create Date: 2026-06-23 15:23:50.055525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bef7ca54143'
down_revision: Union[str, Sequence[str], None] = 'e5439135ac3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('passage_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_passages_id'), 'reading_passages', ['id'], unique=False)
    op.create_table('reading_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_attempts_id'), 'reading_attempts', ['id'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_questions_id'), 'reading_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_questions_id'), table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_index(op.f('ix_reading_attempts_id'), table_name='reading_attempts')
    op.drop_table('reading_attempts')
    op.drop_index(op.f('ix_reading_passages_id'), table_name='reading_passages')
    op.drop_table('reading_passages')
    # ### end Alembic commands ###
