"""add reading models with skill breakdown

Revision ID: 5c873d23c4f4
Revises: 0b684a28f562
Create Date: 2026-06-25 21:51:17.433010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c873d23c4f4'
down_revision: Union[str, Sequence[str], None] = '0b684a28f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_attempts', sa.Column('skill_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reading_attempts', sa.Column('question_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('reading_attempts', 'skill_type')
    op.add_column('reading_questions', sa.Column('skill_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_questions', 'skill_type')
    op.add_column('reading_attempts', sa.Column('skill_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reading_attempts', 'question_results')
    op.drop_column('reading_attempts', 'skill_breakdown')
    # ### end Alembic commands ###
