"""actually_add_listening_table

Revision ID: c43a1c3ca0c1
Revises: 148d2f1f4e7c
Create Date: 2026-07-04 09:46:59.567537

"""
import alembic
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c43a1c3ca0c1'
down_revision: Union[str, Sequence[str], None] = '148d2f1f4e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listeningtest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('questions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'current_listening_level')
    op.drop_column('users', 'current_speaking_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_speaking_level', sa.VARCHAR(), server_default=sa.text("'Beginner'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_listening_level', sa.VARCHAR(), server_default=sa.text("'Beginner'::character varying"), autoincrement=False, nullable=True))
    op.drop_table('listeningtest')
    # ### end Alembic commands ###
