"""add reading models with normalized answer records

Revision ID: c7944f771840
Revises: 5c873d23c4f4
Create Date: 2026-06-29 14:52:21.081340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7944f771840'
down_revision: Union[str, Sequence[str], None] = '5c873d23c4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_answer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['reading_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_answer_records_id'), 'reading_answer_records', ['id'], unique=False)
    op.drop_column('reading_attempts', 'skill_breakdown')
    op.drop_column('reading_attempts', 'question_results')
    op.drop_column('reading_attempts', 'answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_attempts', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('reading_attempts', sa.Column('question_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reading_attempts', sa.Column('skill_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reading_answer_records_id'), table_name='reading_answer_records')
    op.drop_table('reading_answer_records')
    # ### end Alembic commands ###
